import { FormEvent, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import SiteHeader from "@/components/site-header.tsx";
import SiteFooter from "@/components/site-footer.tsx";

export default function ResetPassword() {
  const [params] = useSearchParams(); const token = params.get("token") ?? "";
  const [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""), [done, setDone] = useState(false), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (password !== confirm) return setError("Passwords do not match"); setLoading(true); try { const response = await fetch("/api/auth/reset-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDone(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to reset password"); } finally { setLoading(false); } };
  return <div className="flex min-h-screen flex-col"><SiteHeader /><main className="flex flex-1 items-center justify-center bg-[#0a0316] px-5 py-16"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-black/40 p-8">{done ? <><h1 className="text-2xl font-bold text-white">Password updated</h1><p className="mt-3 text-sm text-white/50">Your password has been changed. You can now sign in.</p><Link to="/login" className="mt-6 block rounded-xl bg-gradient-to-r from-[#7519e9] to-[#df20ba] py-3 text-center text-sm font-bold text-white">Go to login</Link></> : <form onSubmit={submit}><h1 className="text-2xl font-bold text-white">Choose a new password</h1><p className="mt-2 text-sm text-white/50">Use at least 6 characters. This link works once and expires after 24 hours.</p><input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="New password" className="mt-6 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3 text-sm text-white outline-none" /><input required minLength={6} type="password" value={confirm} onChange={e => setConfirm(e.target.value)} placeholder="Confirm new password" className="mt-3 w-full rounded-xl border border-white/15 bg-black/40 px-4 py-3 text-sm text-white outline-none" /><button disabled={loading || !token} className="mt-4 w-full rounded-xl bg-gradient-to-r from-[#7519e9] to-[#df20ba] py-3 text-sm font-bold text-white disabled:opacity-60">{loading ? "Updating…" : "Update password"}</button>{error && <p className="mt-4 rounded-lg bg-red-500/10 p-3 text-center text-xs text-red-200">{error}</p>}</form>}</div></main><SiteFooter /></div>;
}